import os
import sys
from rich import print
from rich.panel import Panel
from rich.console import Console
from rich.traceback import install
import questionary
from utils.utils import custom_style

install(show_locals=True)

sys.path.append(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

console = Console()


def pathTr(display_tools):

  while True:
    user_input = questionary.text(
        "Enter list path of targets to scan (Use list generated by dirfinder):"
    ).ask()
    if user_input is None:
      display_tools()
      return

    base_dir = os.path.abspath(
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "../"))
    if user_input:
      filePath = os.path.abspath(os.path.expanduser(
          user_input)) if os.path.isabs(user_input) else os.path.join(
              base_dir, user_input)
    else:
      continue

    if os.path.isfile(filePath):
      print(f"[bold green]Using file:[/bold green] {filePath}")
      break
    else:
      print(f"[bold red]The file {filePath} does not exist![/bold red]")


def vuln():
  from main import display_tools

  try:
    console.print(
        Panel.fit("[bold red]Welcome to vulnerability scanner![/bold red]\n",
                  title="Vuln",
                  subtitle="Vulnerability Scanner"))

    while True:
      choice = questionary.select("What would you like to do?",
                                  choices=["Path Traversal", "Full", "exit"],
                                  style=custom_style).ask()
      if choice == "exit" or choice is None:
        display_tools()
        return
      elif choice == "Path Traversal":
        pathTr(display_tools)

  except KeyboardInterrupt:
    display_tools()


# https://github.com/Adnanmardini/Python-tool-for-web-vulnerability-scanning/blob/main/app/scanner.py
